// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmxxunektjrkaehfcfva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFteHh1bmVrdGpya2FlaGZjZnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjk5NDMsImV4cCI6MjA2NjYwNTk0M30.Thjhn1IQR8H_s4g-AWyAJeeZYNzPxtQLQc_r1gefaQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);